# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.repository.city_tweet:
        class: AppBundle\Repository\RedisCityTweetRepository
        arguments:
            - "@snc_redis.default"
            - "citytweet"
            - "%city_tweet_ttl%"

    app.provider.twitter:
        class: AppBundle\Service\TwitterProvider\EndroidTwitter
        arguments:
            - "@endroid.twitter"
