# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.repository.city_tweet:
        class: AppBundle\Repository\RedisCityTweetRepository
        arguments:
            - "@snc_redis.default"
            - "citytweet"
            - "%city_tweet_ttl%"

    app.factory.city_tweet:
        class: AppBundle\Factory\CityTweetFactory
        arguments:
            - "%twitter_factory_find_radius%"
            - "%twitter_factory_find_query_size%"
            - "@app.repository.city_tweet"
            - "@app.provider.twitter"

    app.provider.twitter:
        class: AppBundle\Service\TwitterProvider\EndroidTwitter
        arguments:
            - "@endroid.twitter"

    app.provider.geocoder:
        class: AppBundle\Service\GeocoderProvider\TwitterGeocoderProvider
        arguments:
            - "@endroid.twitter"

    app.service.search_city_tweet:
        class: AppBundle\Service\SearchCityTweetService
        arguments:
            - "@app.provider.geocoder"
            - "@app.repository.city_tweet"
            - "@app.factory.city_tweet"
